# Generated by Django 4.1.1 on 2023-01-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=200)),
                ('aircraft_description', models.CharField(max_length=500)),
                ('aircraft_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('aircraft_date', models.DateField()),
                ('completed_occ', models.IntegerField(default=0)),
                ('notes', models.TextField(default='Please leave this blank')),
            ],
        ),
    ]
