# Generated by Django 4.1.1 on 2023-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='year',
            field=models.CharField(db_column='Year', default='', max_length=200),
        ),
    ]
