# Generated by Django 4.1.1 on 2023-02-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='aircraft',
        ),
    ]
