# Generated by Django 4.1.1 on 2023-01-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_date',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_description',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='completed_occ',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='notes',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='cruise_speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fuel_burn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='hourly_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='key_facts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='nautical_miles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='nb_passengers',
            field=models.IntegerField(default=1),
        ),
    ]
