# Generated by Django 4.1.1 on 2023-02-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_accident_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='year',
        ),
        migrations.AlterField(
            model_name='accident',
            name='aircraft_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.aircraft'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='occurrence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='reg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
