# Generated by Django 4.1.1 on 2023-02-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_aircraft_a_check_aircraft_b_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='max_TO_weight_lbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='useful_payload_lbs',
            field=models.IntegerField(default=0),
        ),
    ]
