# Generated by Django 4.1.1 on 2023-02-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_accident_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='aircraft_incident',
            field=models.ForeignKey(db_column='Aircraft Incident', default='', on_delete=django.db.models.deletion.CASCADE, to='api_app.aircraft'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='country',
            field=models.CharField(db_column='Country', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='date',
            field=models.CharField(db_column='Date', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='details',
            field=models.CharField(db_column='details', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='occurrence',
            field=models.CharField(db_column='occurrence', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='accident',
            name='reg',
            field=models.CharField(db_column='Reg', default='', max_length=200),
        ),
    ]
