# Generated by Django 4.1.5 on 2023-01-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_aircraft_aircraft_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='monthly_cost',
            field=models.IntegerField(default=1),
        ),
    ]
