# Generated by Django 4.1.1 on 2023-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_aircraft_max_to_weight_lbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='living_zones',
            field=models.IntegerField(default=0),
        ),
    ]
