# Generated by Django 4.1.1 on 2023-02-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_accident_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='floorplan_drawing',
            field=models.TextField(default=''),
        ),
    ]
