# Generated by Django 4.1.1 on 2023-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_aircraft_floorplan_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='approach_db',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cabin_pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='dispatch_reliability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='flyover_db',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='lateral_db',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='pressure_differential_psi',
            field=models.FloatField(default=0),
        ),
    ]
