# Generated by Django 4.1.1 on 2023-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_aircraft_as_annual_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='max_altitude_feet',
            field=models.FloatField(default=0),
        ),
    ]
