# Generated by Django 4.1.1 on 2023-02-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_aircraft_approach_db_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='API_fleet_count',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='max_TO_weight_lbs',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='useful_payload_lbs',
        ),
    ]
