# Generated by Django 4.1.1 on 2023-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_aircraft_max_altitude_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='high_cruise_knots',
            field=models.FloatField(default=0),
        ),
    ]
