# Generated by Django 4.1.1 on 2023-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_aircraft_high_cruise_knots'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='estimated_annual_flight_hours',
            field=models.IntegerField(default=0),
        ),
    ]
