# Generated by Django 4.1.1 on 2023-02-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_aircraft_estimated_annual_flight_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='estimated_annual_flight_hours',
        ),
    ]
