# Generated by Django 4.1.1 on 2023-02-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_aircraft_aircraft_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='external_baggage_cubicfeet',
            new_name='external_baggage_cubicmeters',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='internal_baggage_cubicfeet',
            new_name='internal_baggage_cubicmeters',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='inflight_accessible_luggage',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='a_check',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='b_check',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='c_check',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='d_check',
            field=models.CharField(default='', max_length=200),
        ),
    ]
