# Generated by Django 4.1.1 on 2023-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_rename_external_baggage_cubicfeet_aircraft_external_baggage_cubicmeters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='max_altitude_meters',
            field=models.FloatField(default=0),
        ),
    ]
