# Generated by Django 4.1.1 on 2023-02-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_aircraft_as_hourly_engine_overhaul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='acquisition_values',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='historical_data',
            field=models.TextField(default=''),
        ),
    ]
