# Generated by Django 4.1.1 on 2023-03-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_aircraft_max_altitude_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='fleet_flight_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
