# Generated by Django 4.1.1 on 2023-02-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_aircraft_acquisition_values_aircraft_historical_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=200)),
                ('reg', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
                ('occurrence', models.CharField(default='', max_length=200)),
                ('details', models.CharField(default='', max_length=200)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.aircraft')),
            ],
        ),
    ]
