# Generated by Django 4.1.1 on 2023-03-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
