from django.db import models


class Aircraft(models.Model):
    aircraft_name = models.CharField(max_length=200, default="")
    model = models.CharField(max_length=200, default="")

    class Category(models.TextChoices):
        Large = "Large"
        Medium = "Medium"
        Light = "Light"
        VLJ = "VLJ"
        Prop = "Prop"
    category = models.TextField(choices=Category.choices, default="")
    max_pax = models.IntegerField(default=0)
    typical_pax = models.IntegerField(default=0)
    cabin_noise = models.IntegerField(default=0)
    cabin_altitude = models.IntegerField(default=0)
    cabin_pressure = models.IntegerField(default=0)
    sea_level_cabin = models.IntegerField(default=0)
    range_NM = models.IntegerField(default=0)
    range_Miles = models.FloatField(default=0)
    range_decrease_per_passenger = models.FloatField(default=0)
    seat_full_range_NM = models.IntegerField(default=0)
    ferr_range_NM = models.IntegerField(default=0)
    high_cruise_MPH = models.FloatField(default=0)
    high_cruise_Mach = models.FloatField(default=0)
    long_range_cruise_knots = models.IntegerField(default=0)
    long_range_cruise_MPH = models.FloatField(default=0)
    long_range_cruise_Mach = models.FloatField(default=0)
    ceiling_feet = models.IntegerField(default=0)
    TO_distance_feet = models.IntegerField(default=0)
    landing_distance_feet = models.IntegerField(default=0)
    rate_climb = models.IntegerField(default=0)
    initial_cruise_altitude = models.IntegerField(default=0)
    ext_length_feet = models.FloatField(default=0)
    wingspan_feet = models.FloatField(default=0)
    exterior_height_feet = models.FloatField(default=0)
    hangar_space_SF = models.FloatField(default=0)
    int_length_feet = models.FloatField(default=0)
    int_width_feet = models.FloatField(default=0)
    int_height_feet = models.FloatField(default=0)
    cabin_volume_CF = models.FloatField(default=0)
    ratio = models.FloatField(default=0)
    door_width_feet = models.FloatField(default=0)
    door_height_feet = models.FloatField(default=0)
    MTOW_lbs = models.IntegerField(default=0)
    max_ramp_weight_lbs = models.IntegerField(default=0)
    max_landing_weight_lbs = models.IntegerField(default=0)
    max_payload_lbs = models.IntegerField(default=0)
    available_fuel_lbs = models.IntegerField(default=0)
    useful_load_lbs = models.IntegerField(default=0)
    basic_operating_weight_lbs = models.IntegerField(default=0)
    baggage_capacity_CF = models.IntegerField(default=0)
    internal_baggage_CF = models.IntegerField(default=0)
    external_baggage_CF = models.IntegerField(default=0)
    baggage_weight_lbs = models.IntegerField(default=0)
    engine_manufacturer = models.CharField(max_length=200, default="")
    engine_model = models.CharField(max_length=200, default="")
    thrust_output_lbs = models.IntegerField(default=0)
    total_thrust_lbs = models.IntegerField(default=0)
    hourly_fuel_burn_GPH = models.IntegerField(default=0)
    lateral_db = models.IntegerField(default=0)
    flyover_db = models.IntegerField(default=0)
    approach_db = models.IntegerField(default=0)
    production_start = models.CharField(max_length=200, default="")
    production_end = models.CharField(max_length=200, default="")
    in_production = models.BooleanField(default=0)
    number_made = models.IntegerField(default=0)
    number_in_service = models.IntegerField(default=0)
    API_fleet_count = models.IntegerField(default=0)
    serial_numbers = models.IntegerField(default=0)
    dispatch_reliability = models.IntegerField(default=0)
    single_pilot_certified = models.BooleanField(default=0)
    toilet = models.BooleanField(default=0)
    shower = models.BooleanField(default=0)
    space_to_sleep = models.BooleanField(default=0)
    dedicated_bed = models.BooleanField(default=0)
    typical_avionic_suite = models.CharField(max_length=200, default="")
    flat_floor = models.BooleanField(default=0)
    inflight_accessible_luggage = models.BooleanField(default=0)
    lving_zone_count = models.IntegerField(default=0)
    initial_crew_training_days = models.IntegerField(default=0)
    recurrent_crew_training_days = models.IntegerField(default=0)
    upgrade_crew_training_days = models.IntegerField(default=0)
    estimated_hourly_charter = models.FloatField(default=0)
    hourly_ownership_rate_NAmerica = models.FloatField(default=0)
    profit_on_charter = models.FloatField(default=0)
    new_purchase = models.FloatField(default=0)
    average_pre_owned = models.FloatField(default=0)
    depreication_rate = models.FloatField(default=0)
    annual_cost = models.FloatField(default=0)

    cabin_altitude_ceiling_meters = models.FloatField(default=0)
    altitude_sea_level_meters = models.FloatField(default=0)
    range_km = models.FloatField(default=0)
    high_speed_cruise_kmh = models.FloatField(default=0)
    long_range_cruise_kmh = models.FloatField(default=0)
    ceiling_meters = models.FloatField(default=0)
    TO_distance_meters = models.FloatField(default=0)
    landing_distance_meters = models.FloatField(default=0)
    rate_climb_meters = models.FloatField(default=0)
    initial_cruise_altitude_meters = models.FloatField(default=0)

    ext_length_meters = models.FloatField(default=0)
    wingspan_meters = models.FloatField(default=0)
    ext_height_meters = models.FloatField(default=0)
    hangar_space_square_meters = models.FloatField(default=0)
    int_length_meters = models.FloatField(default=0)
    int_width_meters = models.FloatField(default=0)
    int_height_meters = models.FloatField(default=0)
    cabin_volume_cubicmeters = models.FloatField(default=0)
    door_width_meters = models.FloatField(default=0)
    door_height_meters = models.FloatField(default=0)

    MTOW_kgs = models.FloatField(default=0)
    max_ramp_weight_kgs = models.FloatField(default=0)
    max_landing_weight_kgs = models.FloatField(default=0)
    max_payload_kgs = models.FloatField(default=0)
    available_fuel_kgs = models.FloatField(default=0)
    useful_payloads_kgs = models.FloatField(default=0)
    basic_operating_weight_kgs = models.FloatField(default=0)
    baggage_capacity_cubicmeters = models.FloatField(default=0)
    internal_baggage_cubicfeet = models.FloatField(default=0)
    external_baggage_cubicfeet = models.FloatField(default=0)
    baggage_weight_kgs = models.FloatField(default=0)

    thrust_output_kgs = models.FloatField(default=0)
    total_thrust_kgs = models.FloatField(default=0)
    hourly_fuel_burn_LPH = models.FloatField(default=0)

    average_mission_length = models.FloatField(default=0)

    key_facts = models.TextField(default="")

    aircraft_image = models.TextField(default="")

    def __str__(self):
        return self.aircraft_name
