from django.views import View
from django.http import JsonResponse
from .models import Aircraft, Accident
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Q


@method_decorator(csrf_exempt, name='dispatch')
class AircraftList(View):
    def get(self, request):
        aircrafts_number = Aircraft.objects.count()
        all_aircrafts = Aircraft.objects.all()
        aircrafts_data = []
        for item in all_aircrafts:
            aircrafts_data.append({
                'aircraft_id': item.id,
                'aircraft_name': item.aircraft_name,
                'aircraft_manufacturer': item.aircraft_manufacturer,
                'key_facts': item.key_facts,
                'model': item.model,
                'category': item.category,
                'max_pax': item.max_pax,
                'typical_pax': item.typical_pax,
                "a_check": item.a_check,
                "b_check": item.b_check,
                "c_check": item.c_check,
                "d_check": item.d_check,
                "living_zones": item.living_zones,
                "baggage_access": item.baggage_access,
                "pressure_differential_psi": item.pressure_differential_psi,
                'cabin_noise': item.cabin_noise,
                'cabin_altitude': item.cabin_altitude,
                'cabin_pressure': item.cabin_pressure,
                'sea_level_cabin': item.sea_level_cabin,
                'range_NM': item.range_NM,
                'range_Miles': item.range_Miles,
                'range_decrease_per_passenger': item.range_decrease_per_passenger,
                'seat_full_range_NM': item.seat_full_range_NM,
                'ferr_range_NM': item.ferr_range_NM,
                'high_cruise_MPH': item.high_cruise_MPH,
                'high_cruise_Mach': item.high_cruise_Mach,
                'long_range_cruise_knots': item.long_range_cruise_knots,
                'long_range_cruise_MPH': item.long_range_cruise_MPH,
                'long_range_cruise_Mach': item.long_range_cruise_Mach,
                'ceiling_feet': item.ceiling_feet,
                'TO_distance_feet': item.TO_distance_feet,
                'landing_distance_feet': item.landing_distance_feet,
                'rate_climb': item.rate_climb,
                'initial_cruise_altitude': item.initial_cruise_altitude,
                'ext_length_feet': item.ext_length_feet,
                'wingspan_feet': item.wingspan_feet,
                'exterior_height_feet': item.exterior_height_feet,
                'hangar_space_SF': item.hangar_space_SF,
                'int_length_feet': item.int_length_feet,
                'int_width_feet': item.int_width_feet,
                'int_height_feet': item.int_height_feet,
                'cabin_volume_CF': item.cabin_volume_CF,
                'ratio': item.ratio,
                'door_width_feet': item.door_width_feet,
                'door_height_feet': item.door_height_feet,
                'MTOW_lbs': item.MTOW_lbs,
                'max_ramp_weight_lbs': item.max_ramp_weight_lbs,
                'max_landing_weight_lbs': item.max_landing_weight_lbs,
                'max_payload_lbs': item.max_payload_lbs,
                'available_fuel_lbs': item.available_fuel_lbs,
                'useful_load_lbs': item.useful_load_lbs,
                'basic_operating_weight_lbs': item.basic_operating_weight_lbs,
                'baggage_capacity_CF': item.baggage_capacity_CF,
                'internal_baggage_CF': item.internal_baggage_CF,
                'external_baggage_CF': item.external_baggage_CF,
                'baggage_weight_lbs': item.baggage_weight_lbs,
                'engine_manufacturer': item.engine_manufacturer,
                'engine_model': item.engine_model,
                'thrust_output_lbs': item.thrust_output_lbs,
                'total_thrust_lbs': item.total_thrust_lbs,
                'hourly_fuel_burn_GPH': item.hourly_fuel_burn_GPH,
                'lateral_db': item.lateral_db,
                'flyover_db': item.flyover_db,
                'approach_db': item.approach_db,
                'production_start': item.production_start,
                'production_end': item.production_end,
                'in_production': item.in_production,
                "high_cruise_knots": item.high_cruise_knots,
                'number_made': item.number_made,
                'number_in_service': item.number_in_service,

                'serial_numbers': item.serial_numbers,
                'minimum_pilots': item.minimum_pilots,
                'dispatch_reliability': item.dispatch_reliability,
                'single_pilot_certified': item.single_pilot_certified,
                'toilet': item.toilet,
                'shower': item.shower,
                'space_to_sleep': item.space_to_sleep,
                'dedicated_bed': item.dedicated_bed,
                'typical_avionic_suite': item.typical_avionic_suite,
                'flat_floor': item.flat_floor,
                'inflight_accessible_luggage': item.inflight_accessible_luggage,
                'lving_zone_count': item.lving_zone_count,
                'initial_crew_training_days': item.initial_crew_training_days,
                'recurrent_crew_training_days': item.recurrent_crew_training_days,
                'upgrade_crew_training_days': item.upgrade_crew_training_days,
                'estimated_hourly_charter': item.estimated_hourly_charter,
                'hourly_ownership_rate_NAmerica': item.hourly_ownership_rate_NAmerica,
                'profit_on_charter': item.profit_on_charter,
                'new_purchase': item.new_purchase,
                'average_pre_owned': item.average_pre_owned,
                'depreication_rate': item.depreication_rate,
                'annual_cost': item.annual_cost,
                'cabin_altitude_ceiling_meters': item.cabin_altitude_ceiling_meters,
                'altitude_sea_level_meters': item.altitude_sea_level_meters,
                'range_km': item.range_km,
                'max_altitude_feet': item.max_altitude_feet,
                'high_speed_cruise_kmh': item.high_speed_cruise_kmh,
                'long_range_cruise_kmh': item.long_range_cruise_kmh,
                'ceiling_meters': item.ceiling_meters,
                'TO_distance_meters': item.TO_distance_meters,
                'landing_distance_meters': item.landing_distance_meters,
                'rate_climb_meters': item.rate_climb_meters,
                'initial_cruise_altitude_meters': item.initial_cruise_altitude_meters,
                'ext_length_meters': item.ext_length_meters,
                'wingspan_meters': item.wingspan_meters,
                'ext_height_meters': item.ext_height_meters,
                'hangar_space_square_meters': item.hangar_space_square_meters,
                'int_length_meters': item.int_length_meters,
                'int_width_meters': item.int_width_meters,
                'int_height_meters': item.int_height_meters,
                'cabin_volume_cubicmeters': item.cabin_volume_cubicmeters,
                'door_width_meters': item.door_width_meters,
                'door_height_meters': item.door_height_meters,
                'MTOW_kgs': item.MTOW_kgs,
                'max_ramp_weight_kgs': item.max_ramp_weight_kgs,
                'max_landing_weight_kgs': item.max_landing_weight_kgs,
                'max_payload_kgs': item.max_payload_kgs,
                'available_fuel_kgs': item.available_fuel_kgs,
                'useful_payloads_kgs': item.useful_payloads_kgs,
                'basic_operating_weight_kgs': item.basic_operating_weight_kgs,
                'baggage_capacity_cubicmeters': item.baggage_capacity_cubicmeters,
                'internal_baggage_cubicfeet': item.internal_baggage_cubicfeet,
                'external_baggage_cubicfeet': item.external_baggage_cubicfeet,
                'baggage_weight_kgs': item.baggage_weight_kgs,
                'thrust_output_kgs': item.thrust_output_kgs,
                'total_thrust_kgs': item.total_thrust_kgs,
                'hourly_fuel_burn_LPH': item.hourly_fuel_burn_LPH,
                'average_mission_length': item.average_mission_length,
                'floorplan_drawing': item.floorplan_drawing,
                'image_name': item.aircraft_image,

                'NA_annual_captain': item.NA_annual_captain,
                'NA_annual_first_office': item.NA_annual_first_office,
                'NA_annual_employee_benefits': item.NA_annual_employee_benefits,
                'NA_annual_crew_training': item.NA_annual_crew_training,
                'NA_annual_hangar': item.NA_annual_hangar,
                'NA_annual_insurance_hull': item.NA_annual_insurance_hull,
                'NA_annual_insurance_liability': item.NA_annual_insurance_liability,
                'NA_annual_management': item.NA_annual_management,
                'NA_annual_misc': item.NA_annual_misc,
                'NA_annual_deprecation': item.NA_annual_deprecation,
                'NA_annual_total': item.NA_annual_total,
                'EU_annual_captain': item.EU_annual_captain,
                'EU_annual_first_office': item.EU_annual_first_office,
                'EU_annual_employee_benefits': item.EU_annual_employee_benefits,
                'EU_annual_crew_training': item.EU_annual_crew_training,
                'EU_annual_hangar': item.EU_annual_hangar,
                'EU_annual_insurance_hull': item.EU_annual_insurance_hull,
                'EU_annual_insurance_liability': item.EU_annual_insurance_liability,
                'EU_annual_management': item.EU_annual_management,
                'EU_annual_misc': item.EU_annual_misc,
                'EU_annual_deprecation': item.EU_annual_deprecation,
                'EU_annual_total': item.EU_annual_total,
                'SA_annual_captain': item.SA_annual_captain,
                'SA_annual_first_office': item.SA_annual_first_office,
                'SA_annual_employee_benefits': item.SA_annual_employee_benefits,
                'SA_annual_crew_training': item.SA_annual_crew_training,
                'SA_annual_hangar': item.SA_annual_hangar,
                'SA_annual_insurance_hull': item.SA_annual_insurance_hull,
                'SA_annual_insurance_liability': item.SA_annual_insurance_liability,
                'SA_annual_management': item.SA_annual_management,
                'SA_annual_misc': item.SA_annual_misc,
                'SA_annual_deprecation': item.SA_annual_deprecation,
                'SA_annual_total': item.SA_annual_total,
                'AS_annual_captain': item.AS_annual_captain,
                'AS_annual_first_office': item.AS_annual_first_office,
                'AS_annual_employee_benefits': item.AS_annual_employee_benefits,
                'AS_annual_crew_training': item.AS_annual_crew_training,
                'AS_annual_hangar': item.AS_annual_hangar,
                'AS_annual_insurance_hull': item.AS_annual_insurance_hull,
                'AS_annual_insurance_liability': item.AS_annual_insurance_liability,
                'AS_annual_management': item.AS_annual_management,
                'AS_annual_misc': item.AS_annual_misc,
                'AS_annual_deprecation': item.AS_annual_deprecation,
                'AS_annual_total': item.AS_annual_total,
                'NA_hourly_fuel': item.NA_hourly_fuel,
                'NA_hourly_maintenance': item.NA_hourly_maintenance,
                'NA_hourly_engine_overhaul': item.NA_hourly_engine_overhaul,
                'NA_hourly_ground_fees': item.NA_hourly_ground_fees,
                'NA_hourly_misc': item.NA_hourly_misc,
                'NA_hourly_total': item.NA_hourly_total,
                'EU_hourly_fuel': item.EU_hourly_fuel,
                'EU_hourly_maintenance': item.EU_hourly_maintenance,
                'EU_hourly_engine_overhaul': item.EU_hourly_engine_overhaul,
                'EU_hourly_ground_fees': item.EU_hourly_ground_fees,
                'EU_hourly_misc': item.EU_hourly_misc,
                'EU_hourly_total': item.EU_hourly_total,
                'SA_hourly_fuel': item.SA_hourly_fuel,
                'SA_hourly_maintenance': item.SA_hourly_maintenance,
                'SA_hourly_engine_overhaul': item.SA_hourly_engine_overhaul,
                'SA_hourly_ground_fees': item.SA_hourly_ground_fees,
                'SA_hourly_misc': item.SA_hourly_misc,
                'SA_hourly_total': item.SA_hourly_total,
                'AS_hourly_fuel': item.AS_hourly_fuel,
                'AS_hourly_maintenance': item.AS_hourly_maintenance,
                'AS_hourly_engine_overhaul': item.AS_hourly_engine_overhaul,
                'AS_hourly_ground_fees': item.AS_hourly_ground_fees,
                'AS_hourly_misc': item.AS_hourly_misc,
                'AS_hourly_total': item.AS_hourly_total,
                'NA_fuel_costs': item.NA_fuel_costs,
                'EU_fuel_costs': item.EU_fuel_costs,
                'SA_fuel_costs': item.SA_fuel_costs,
                'AS_fuel_costs': item.AS_fuel_costs,
                'acquisition_values': item.acquisition_values,
                'historical_data': item.historical_data,
            })

        data = {
            'aircrafts': aircrafts_data,
            'count': aircrafts_number,
        }

        return JsonResponse(data)


@method_decorator(csrf_exempt, name="dispatch")
class AircraftSearch(View):
    def get(self, request):
        # request_data = request.GET if request.GET.get("aircraft_name") else request.data
        print(request)
        aircraft_name = request.GET.get("aircraft_name")
        category = request.GET.get("category")
        aircraft_manufacturer = request.GET.get("aircraft_manufacturer")
        in_production = request.GET.get("in_production")
        max_pax = request.GET.get("max_pax")
        range_NM = request.GET.get("range_NM")
        high_cruise_knots = request.GET.get("high_cruise_knots")
        max_altitude_feet = request.GET.get("max_altitude_feet")
        hourly_fuel_burn_GPH = request.GET.get("hourly_fuel_burn_GPH")
        baggage_capacity_CF = request.GET.get("baggage_capacity_CF")
        TO_distance_feet = request.GET.get("TO_distance_feet")
        landing_distance_feet = request.GET.get("landing_distance_feet")
        annual_cost = request.GET.get("annual_cost")
        estimated_hourly_charter = request.GET.get("estimated_hourly_charter")
        new_purchase = request.GET.get("new_purchase")
        average_pre_owned = request.GET.get("average_pre_owned")
        try:
            results = Aircraft.objects.filter(Q
                                              (aircraft_name__icontains=aircraft_name, category__icontains=category, aircraft_manufacturer__icontains=aircraft_manufacturer, in_production__icontains=in_production, ) & Q(max_pax__lte=max_pax) & Q(range_NM__lte=range_NM) & Q(high_cruise_knots__lte=high_cruise_knots) & Q(max_altitude_feet__lte=max_altitude_feet) & Q(hourly_fuel_burn_GPH__lte=hourly_fuel_burn_GPH) & Q(baggage_capacity_CF__lte=baggage_capacity_CF) & Q(TO_distance_feet__lte=TO_distance_feet) & Q(landing_distance_feet__lte=landing_distance_feet) & Q(annual_cost__lte=annual_cost) & Q(estimated_hourly_charter__lte=estimated_hourly_charter) & Q(new_purchase__lte=new_purchase) & Q(average_pre_owned__lte=average_pre_owned))
        except Exception:
            print("ERROR: Failed to get object from database")
            return HttpResponse("Object not found !")
        else:
            data = []
            for item in results:
                data.append(
                    {
                        "aircraft_id": item.id,
                        "aircraft_name": item.aircraft_name,
                        "key_facts": item.key_facts,
                        "model": item.model,
                        "category": item.category,
                        'aircraft_manufacturer': item.aircraft_manufacturer,
                        "a_check": item.a_check,
                        "b_check": item.b_check,
                        "c_check": item.c_check,
                        "d_check": item.d_check,
                        "living_zones": item.living_zones,
                        "baggage_access": item.baggage_access,
                        "pressure_differential_psi": item.pressure_differential_psi,
                        "max_pax": item.max_pax,
                        "typical_pax": item.typical_pax,
                        "cabin_noise": item.cabin_noise,
                        "cabin_altitude": item.cabin_altitude,
                        "cabin_pressure": item.cabin_pressure,
                        "sea_level_cabin": item.sea_level_cabin,
                        "range_NM": item.range_NM,
                        "range_Miles": item.range_Miles,
                        "range_decrease_per_passenger": item.range_decrease_per_passenger,
                        "seat_full_range_NM": item.seat_full_range_NM,
                        "ferr_range_NM": item.ferr_range_NM,
                        "high_cruise_MPH": item.high_cruise_MPH,
                        "high_cruise_Mach": item.high_cruise_Mach,
                        "high_cruise_knots": item.high_cruise_knots,
                        "long_range_cruise_knots": item.long_range_cruise_knots,
                        "long_range_cruise_MPH": item.long_range_cruise_MPH,
                        "long_range_cruise_Mach": item.long_range_cruise_Mach,
                        "ceiling_feet": item.ceiling_feet,
                        "TO_distance_feet": item.TO_distance_feet,
                        "landing_distance_feet": item.landing_distance_feet,
                        "rate_climb": item.rate_climb,
                        "initial_cruise_altitude": item.initial_cruise_altitude,
                        "ext_length_feet": item.ext_length_feet,
                        "wingspan_feet": item.wingspan_feet,
                        "exterior_height_feet": item.exterior_height_feet,
                        "hangar_space_SF": item.hangar_space_SF,
                        "int_length_feet": item.int_length_feet,
                        "int_width_feet": item.int_width_feet,
                        "int_height_feet": item.int_height_feet,
                        "cabin_volume_CF": item.cabin_volume_CF,
                        "ratio": item.ratio,
                        'max_altitude_feet': item.max_altitude_feet,
                        "door_width_feet": item.door_width_feet,
                        "door_height_feet": item.door_height_feet,
                        "MTOW_lbs": item.MTOW_lbs,
                        "max_ramp_weight_lbs": item.max_ramp_weight_lbs,
                        "max_landing_weight_lbs": item.max_landing_weight_lbs,
                        "max_payload_lbs": item.max_payload_lbs,
                        "available_fuel_lbs": item.available_fuel_lbs,
                        "useful_load_lbs": item.useful_load_lbs,
                        "basic_operating_weight_lbs": item.basic_operating_weight_lbs,
                        "baggage_capacity_CF": item.baggage_capacity_CF,
                        "internal_baggage_CF": item.internal_baggage_CF,
                        "external_baggage_CF": item.external_baggage_CF,
                        "baggage_weight_lbs": item.baggage_weight_lbs,
                        "engine_manufacturer": item.engine_manufacturer,
                        "engine_model": item.engine_model,
                        'minimum_pilots': item.minimum_pilots,
                        "thrust_output_lbs": item.thrust_output_lbs,
                        "total_thrust_lbs": item.total_thrust_lbs,
                        "hourly_fuel_burn_GPH": item.hourly_fuel_burn_GPH,
                        "lateral_db": item.lateral_db,
                        "flyover_db": item.flyover_db,
                        "approach_db": item.approach_db,
                        "production_start": item.production_start,
                        "production_end": item.production_end,
                        "in_production": item.in_production,
                        "number_made": item.number_made,
                        "number_in_service": item.number_in_service,
                        "serial_numbers": item.serial_numbers,
                        "dispatch_reliability": item.dispatch_reliability,
                        "single_pilot_certified": item.single_pilot_certified,
                        "toilet": item.toilet,
                        "shower": item.shower,
                        "space_to_sleep": item.space_to_sleep,
                        "dedicated_bed": item.dedicated_bed,
                        "typical_avionic_suite": item.typical_avionic_suite,
                        "flat_floor": item.flat_floor,
                        "inflight_accessible_luggage": item.inflight_accessible_luggage,
                        "lving_zone_count": item.lving_zone_count,
                        "initial_crew_training_days": item.initial_crew_training_days,
                        "recurrent_crew_training_days": item.recurrent_crew_training_days,
                        "upgrade_crew_training_days": item.upgrade_crew_training_days,
                        "estimated_hourly_charter": item.estimated_hourly_charter,
                        "hourly_ownership_rate_NAmerica": item.hourly_ownership_rate_NAmerica,
                        "profit_on_charter": item.profit_on_charter,
                        "new_purchase": item.new_purchase,
                        "average_pre_owned": item.average_pre_owned,
                        "depreication_rate": item.depreication_rate,
                        "annual_cost": item.annual_cost,
                        "cabin_altitude_ceiling_meters": item.cabin_altitude_ceiling_meters,
                        "altitude_sea_level_meters": item.altitude_sea_level_meters,
                        "range_km": item.range_km,
                        "high_speed_cruise_kmh": item.high_speed_cruise_kmh,
                        "long_range_cruise_kmh": item.long_range_cruise_kmh,
                        "ceiling_meters": item.ceiling_meters,
                        "TO_distance_meters": item.TO_distance_meters,
                        "landing_distance_meters": item.landing_distance_meters,
                        "rate_climb_meters": item.rate_climb_meters,
                        "initial_cruise_altitude_meters": item.initial_cruise_altitude_meters,
                        "ext_length_meters": item.ext_length_meters,
                        "wingspan_meters": item.wingspan_meters,
                        "ext_height_meters": item.ext_height_meters,
                        "hangar_space_square_meters": item.hangar_space_square_meters,
                        "int_length_meters": item.int_length_meters,
                        "int_width_meters": item.int_width_meters,
                        "int_height_meters": item.int_height_meters,
                        "cabin_volume_cubicmeters": item.cabin_volume_cubicmeters,
                        "door_width_meters": item.door_width_meters,
                        "door_height_meters": item.door_height_meters,
                        "MTOW_kgs": item.MTOW_kgs,
                        "max_ramp_weight_kgs": item.max_ramp_weight_kgs,
                        "max_landing_weight_kgs": item.max_landing_weight_kgs,
                        "max_payload_kgs": item.max_payload_kgs,
                        "available_fuel_kgs": item.available_fuel_kgs,
                        "useful_payloads_kgs": item.useful_payloads_kgs,
                        "basic_operating_weight_kgs": item.basic_operating_weight_kgs,
                        "baggage_capacity_cubicmeters": item.baggage_capacity_cubicmeters,
                        "internal_baggage_cubicfeet": item.internal_baggage_cubicfeet,
                        "external_baggage_cubicfeet": item.external_baggage_cubicfeet,
                        "baggage_weight_kgs": item.baggage_weight_kgs,
                        "thrust_output_kgs": item.thrust_output_kgs,
                        "total_thrust_kgs": item.total_thrust_kgs,
                        "hourly_fuel_burn_LPH": item.hourly_fuel_burn_LPH,
                        "average_mission_length": item.average_mission_length,
                        'floorplan_drawing': item.floorplan_drawing,
                        "image_name": item.aircraft_image,
                        'NA_annual_captain': item.NA_annual_captain,
                        'NA_annual_first_office': item.NA_annual_first_office,
                        'NA_annual_employee_benefits': item.NA_annual_employee_benefits,
                        'NA_annual_crew_training': item.NA_annual_crew_training,
                        'NA_annual_hangar': item.NA_annual_hangar,
                        'NA_annual_insurance_hull': item.NA_annual_insurance_hull,
                        'NA_annual_insurance_liability': item.NA_annual_insurance_liability,
                        'NA_annual_management': item.NA_annual_management,
                        'NA_annual_misc': item.NA_annual_misc,
                        'NA_annual_deprecation': item.NA_annual_deprecation,
                        'NA_annual_total': item.NA_annual_total,
                        'EU_annual_captain': item.EU_annual_captain,
                        'EU_annual_first_office': item.EU_annual_first_office,
                        'EU_annual_employee_benefits': item.EU_annual_employee_benefits,
                        'EU_annual_crew_training': item.EU_annual_crew_training,
                        'EU_annual_hangar': item.EU_annual_hangar,
                        'EU_annual_insurance_hull': item.EU_annual_insurance_hull,
                        'EU_annual_insurance_liability': item.EU_annual_insurance_liability,
                        'EU_annual_management': item.EU_annual_management,
                        'EU_annual_misc': item.EU_annual_misc,
                        'EU_annual_deprecation': item.EU_annual_deprecation,
                        'EU_annual_total': item.EU_annual_total,
                        'SA_annual_captain': item.SA_annual_captain,
                        'SA_annual_first_office': item.SA_annual_first_office,
                        'SA_annual_employee_benefits': item.SA_annual_employee_benefits,
                        'SA_annual_crew_training': item.SA_annual_crew_training,
                        'SA_annual_hangar': item.SA_annual_hangar,
                        'SA_annual_insurance_hull': item.SA_annual_insurance_hull,
                        'SA_annual_insurance_liability': item.SA_annual_insurance_liability,
                        'SA_annual_management': item.SA_annual_management,
                        'SA_annual_misc': item.SA_annual_misc,
                        'SA_annual_deprecation': item.SA_annual_deprecation,
                        'SA_annual_total': item.SA_annual_total,
                        'AS_annual_captain': item.AS_annual_captain,
                        'AS_annual_first_office': item.AS_annual_first_office,
                        'AS_annual_employee_benefits': item.AS_annual_employee_benefits,
                        'AS_annual_crew_training': item.AS_annual_crew_training,
                        'AS_annual_hangar': item.AS_annual_hangar,
                        'AS_annual_insurance_hull': item.AS_annual_insurance_hull,
                        'AS_annual_insurance_liability': item.AS_annual_insurance_liability,
                        'AS_annual_management': item.AS_annual_management,
                        'AS_annual_misc': item.AS_annual_misc,
                        'AS_annual_deprecation': item.AS_annual_deprecation,
                        'AS_annual_total': item.AS_annual_total,
                        'NA_fuel_costs': item.NA_fuel_costs,
                        'EU_fuel_costs': item.EU_fuel_costs,
                        'SA_fuel_costs': item.SA_fuel_costs,
                        'AS_fuel_costs': item.AS_fuel_costs,
                        'NA_hourly_fuel': item.NA_hourly_fuel,
                        'NA_hourly_maintenance': item.NA_hourly_maintenance,
                        'NA_hourly_engine_overhaul': item.NA_hourly_engine_overhaul,
                        'NA_hourly_ground_fees': item.NA_hourly_ground_fees,
                        'NA_hourly_misc': item.NA_hourly_misc,
                        'NA_hourly_total': item.NA_hourly_total,
                        'EU_hourly_fuel': item.EU_hourly_fuel,
                        'EU_hourly_maintenance': item.EU_hourly_maintenance,
                        'EU_hourly_engine_overhaul': item.EU_hourly_engine_overhaul,
                        'EU_hourly_ground_fees': item.EU_hourly_ground_fees,
                        'EU_hourly_misc': item.EU_hourly_misc,
                        'EU_hourly_total': item.EU_hourly_total,
                        'SA_hourly_fuel': item.SA_hourly_fuel,
                        'SA_hourly_maintenance': item.SA_hourly_maintenance,
                        'SA_hourly_engine_overhaul': item.SA_hourly_engine_overhaul,
                        'SA_hourly_ground_fees': item.SA_hourly_ground_fees,
                        'SA_hourly_misc': item.SA_hourly_misc,
                        'SA_hourly_total': item.SA_hourly_total,
                        'AS_hourly_fuel': item.AS_hourly_fuel,
                        'AS_hourly_maintenance': item.AS_hourly_maintenance,
                        'AS_hourly_engine_overhaul': item.AS_hourly_engine_overhaul,
                        'AS_hourly_ground_fees': item.AS_hourly_ground_fees,
                        'AS_hourly_misc': item.AS_hourly_misc,
                        'AS_hourly_total': item.AS_hourly_total,
                        'acquisition_values': item.acquisition_values,
                        'historical_data': item.historical_data,
                    }
                )

        searchdata = {
            'aircrafts': data,
        }

        return JsonResponse(searchdata)


@method_decorator(csrf_exempt, name='dispatch')
class AircraftById(View):
    def get(self, request, id):
        item = Aircraft.objects.get(id=id)
        aircraft_data = []
        aircraft_data.append({
            'aircraft_id': item.id,
            'aircraft_name': item.aircraft_name,
            "a_check": item.a_check,
            "b_check": item.b_check,
            "c_check": item.c_check,
            "d_check": item.d_check,
            "living_zones": item.living_zones,
            "baggage_access": item.baggage_access,
            "pressure_differential_psi": item.pressure_differential_psi,
            'key_facts': item.key_facts,
            'model': item.model,
            'category': item.category,
            'aircraft_manufacturer': item.aircraft_manufacturer,
            'max_pax': item.max_pax,
            'typical_pax': item.typical_pax,
            'cabin_noise': item.cabin_noise,
            'cabin_altitude': item.cabin_altitude,
            'cabin_pressure': item.cabin_pressure,
            'sea_level_cabin': item.sea_level_cabin,
            'range_NM': item.range_NM,
            'range_Miles': item.range_Miles,
            'range_decrease_per_passenger': item.range_decrease_per_passenger,
            'seat_full_range_NM': item.seat_full_range_NM,
            'ferr_range_NM': item.ferr_range_NM,
            'high_cruise_MPH': item.high_cruise_MPH,
            'high_cruise_Mach': item.high_cruise_Mach,
            'long_range_cruise_knots': item.long_range_cruise_knots,
            'long_range_cruise_MPH': item.long_range_cruise_MPH,
            'long_range_cruise_Mach': item.long_range_cruise_Mach,
            'max_altitude_feet': item.max_altitude_feet,
            'ceiling_feet': item.ceiling_feet,
            'minimum_pilots': item.minimum_pilots,
            'TO_distance_feet': item.TO_distance_feet,
            'landing_distance_feet': item.landing_distance_feet,
            'rate_climb': item.rate_climb,
            'initial_cruise_altitude': item.initial_cruise_altitude,
            'ext_length_feet': item.ext_length_feet,
            'wingspan_feet': item.wingspan_feet,
            'exterior_height_feet': item.exterior_height_feet,
            'hangar_space_SF': item.hangar_space_SF,
            'int_length_feet': item.int_length_feet,
            'int_width_feet': item.int_width_feet,
            'int_height_feet': item.int_height_feet,
            'cabin_volume_CF': item.cabin_volume_CF,
            'ratio': item.ratio,
            'door_width_feet': item.door_width_feet,
            'door_height_feet': item.door_height_feet,
            'MTOW_lbs': item.MTOW_lbs,
            'max_ramp_weight_lbs': item.max_ramp_weight_lbs,
            'max_landing_weight_lbs': item.max_landing_weight_lbs,
            'max_payload_lbs': item.max_payload_lbs,
            'available_fuel_lbs': item.available_fuel_lbs,
            'useful_load_lbs': item.useful_load_lbs,
            'basic_operating_weight_lbs': item.basic_operating_weight_lbs,
            'baggage_capacity_CF': item.baggage_capacity_CF,
            'internal_baggage_CF': item.internal_baggage_CF,
            'external_baggage_CF': item.external_baggage_CF,
            'baggage_weight_lbs': item.baggage_weight_lbs,
            'engine_manufacturer': item.engine_manufacturer,
            'engine_model': item.engine_model,
            'thrust_output_lbs': item.thrust_output_lbs,
            'total_thrust_lbs': item.total_thrust_lbs,
            'hourly_fuel_burn_GPH': item.hourly_fuel_burn_GPH,
            'lateral_db': item.lateral_db,
            'flyover_db': item.flyover_db,
            'approach_db': item.approach_db,
            'production_start': item.production_start,
            'production_end': item.production_end,
            'in_production': item.in_production,
            'number_made': item.number_made,
            'number_in_service': item.number_in_service,

            'serial_numbers': item.serial_numbers,
            'dispatch_reliability': item.dispatch_reliability,
            'single_pilot_certified': item.single_pilot_certified,
            'toilet': item.toilet,
            'shower': item.shower,
            'space_to_sleep': item.space_to_sleep,
            'dedicated_bed': item.dedicated_bed,
            'typical_avionic_suite': item.typical_avionic_suite,
            'flat_floor': item.flat_floor,
            'inflight_accessible_luggage': item.inflight_accessible_luggage,
            'lving_zone_count': item.lving_zone_count,
            'initial_crew_training_days': item.initial_crew_training_days,
            'recurrent_crew_training_days': item.recurrent_crew_training_days,
            'upgrade_crew_training_days': item.upgrade_crew_training_days,
            'estimated_hourly_charter': item.estimated_hourly_charter,
            'hourly_ownership_rate_NAmerica': item.hourly_ownership_rate_NAmerica,
            'profit_on_charter': item.profit_on_charter,
            'new_purchase': item.new_purchase,
            'average_pre_owned': item.average_pre_owned,
            'depreication_rate': item.depreication_rate,
            'annual_cost': item.annual_cost,
            'cabin_altitude_ceiling_meters': item.cabin_altitude_ceiling_meters,
            'altitude_sea_level_meters': item.altitude_sea_level_meters,
            'range_km': item.range_km,
            'high_speed_cruise_kmh': item.high_speed_cruise_kmh,
            'long_range_cruise_kmh': item.long_range_cruise_kmh,
            'ceiling_meters': item.ceiling_meters,
            'TO_distance_meters': item.TO_distance_meters,
            'landing_distance_meters': item.landing_distance_meters,
            'rate_climb_meters': item.rate_climb_meters,
            'initial_cruise_altitude_meters': item.initial_cruise_altitude_meters,
            'ext_length_meters': item.ext_length_meters,
            'wingspan_meters': item.wingspan_meters,
            'ext_height_meters': item.ext_height_meters,
            'hangar_space_square_meters': item.hangar_space_square_meters,
            'int_length_meters': item.int_length_meters,
            'int_width_meters': item.int_width_meters,
            'int_height_meters': item.int_height_meters,
            'cabin_volume_cubicmeters': item.cabin_volume_cubicmeters,
            'door_width_meters': item.door_width_meters,
            'door_height_meters': item.door_height_meters,
            'MTOW_kgs': item.MTOW_kgs,
            "high_cruise_knots": item.high_cruise_knots,
            'max_ramp_weight_kgs': item.max_ramp_weight_kgs,
            'max_landing_weight_kgs': item.max_landing_weight_kgs,
            'max_payload_kgs': item.max_payload_kgs,
            'available_fuel_kgs': item.available_fuel_kgs,
            'useful_payloads_kgs': item.useful_payloads_kgs,
            'basic_operating_weight_kgs': item.basic_operating_weight_kgs,
            'baggage_capacity_cubicmeters': item.baggage_capacity_cubicmeters,
            'internal_baggage_cubicfeet': item.internal_baggage_cubicfeet,
            'external_baggage_cubicfeet': item.external_baggage_cubicfeet,
            'baggage_weight_kgs': item.baggage_weight_kgs,
            'thrust_output_kgs': item.thrust_output_kgs,
            'total_thrust_kgs': item.total_thrust_kgs,
            'hourly_fuel_burn_LPH': item.hourly_fuel_burn_LPH,
            'average_mission_length': item.average_mission_length,
            'floorplan_drawing': item.floorplan_drawing,
            'image_name': item.aircraft_image,
            'NA_annual_captain': item.NA_annual_captain,
            'NA_annual_first_office': item.NA_annual_first_office,
            'NA_annual_employee_benefits': item.NA_annual_employee_benefits,
            'NA_annual_crew_training': item.NA_annual_crew_training,
            'NA_annual_hangar': item.NA_annual_hangar,
            'NA_annual_insurance_hull': item.NA_annual_insurance_hull,
            'NA_annual_insurance_liability': item.NA_annual_insurance_liability,
            'NA_annual_management': item.NA_annual_management,
            'NA_annual_misc': item.NA_annual_misc,
            'NA_annual_deprecation': item.NA_annual_deprecation,
            'NA_annual_total': item.NA_annual_total,
            'EU_annual_captain': item.EU_annual_captain,
            'EU_annual_first_office': item.EU_annual_first_office,
            'EU_annual_employee_benefits': item.EU_annual_employee_benefits,
            'EU_annual_crew_training': item.EU_annual_crew_training,
            'EU_annual_hangar': item.EU_annual_hangar,
            'EU_annual_insurance_hull': item.EU_annual_insurance_hull,
            'EU_annual_insurance_liability': item.EU_annual_insurance_liability,
            'EU_annual_management': item.EU_annual_management,
            'EU_annual_misc': item.EU_annual_misc,
            'EU_annual_deprecation': item.EU_annual_deprecation,
            'EU_annual_total': item.EU_annual_total,
            'SA_annual_captain': item.SA_annual_captain,
            'SA_annual_first_office': item.SA_annual_first_office,
            'SA_annual_employee_benefits': item.SA_annual_employee_benefits,
            'SA_annual_crew_training': item.SA_annual_crew_training,
            'SA_annual_hangar': item.SA_annual_hangar,
            'SA_annual_insurance_hull': item.SA_annual_insurance_hull,
            'SA_annual_insurance_liability': item.SA_annual_insurance_liability,
            'SA_annual_management': item.SA_annual_management,
            'SA_annual_misc': item.SA_annual_misc,
            'SA_annual_deprecation': item.SA_annual_deprecation,
            'SA_annual_total': item.SA_annual_total,
            'AS_annual_captain': item.AS_annual_captain,
            'AS_annual_first_office': item.AS_annual_first_office,
            'AS_annual_employee_benefits': item.AS_annual_employee_benefits,
            'AS_annual_crew_training': item.AS_annual_crew_training,
            'AS_annual_hangar': item.AS_annual_hangar,
            'AS_annual_insurance_hull': item.AS_annual_insurance_hull,
            'AS_annual_insurance_liability': item.AS_annual_insurance_liability,
            'AS_annual_management': item.AS_annual_management,
            'AS_annual_misc': item.AS_annual_misc,
            'AS_annual_deprecation': item.AS_annual_deprecation,
            'AS_annual_total': item.AS_annual_total,
            'NA_fuel_costs': item.NA_fuel_costs,
            'EU_fuel_costs': item.EU_fuel_costs,
            'SA_fuel_costs': item.SA_fuel_costs,
            'AS_fuel_costs': item.AS_fuel_costs,
            'NA_hourly_fuel': item.NA_hourly_fuel,
            'NA_hourly_maintenance': item.NA_hourly_maintenance,
            'NA_hourly_engine_overhaul': item.NA_hourly_engine_overhaul,
            'NA_hourly_ground_fees': item.NA_hourly_ground_fees,
            'NA_hourly_misc': item.NA_hourly_misc,
            'NA_hourly_total': item.NA_hourly_total,
            'EU_hourly_fuel': item.EU_hourly_fuel,
            'EU_hourly_maintenance': item.EU_hourly_maintenance,
            'EU_hourly_engine_overhaul': item.EU_hourly_engine_overhaul,
            'EU_hourly_ground_fees': item.EU_hourly_ground_fees,
            'EU_hourly_misc': item.EU_hourly_misc,
            'EU_hourly_total': item.EU_hourly_total,
            'SA_hourly_fuel': item.SA_hourly_fuel,
            'SA_hourly_maintenance': item.SA_hourly_maintenance,
            'SA_hourly_engine_overhaul': item.SA_hourly_engine_overhaul,
            'SA_hourly_ground_fees': item.SA_hourly_ground_fees,
            'SA_hourly_misc': item.SA_hourly_misc,
            'SA_hourly_total': item.SA_hourly_total,
            'AS_hourly_fuel': item.AS_hourly_fuel,
            'AS_hourly_maintenance': item.AS_hourly_maintenance,
            'AS_hourly_engine_overhaul': item.AS_hourly_engine_overhaul,
            'AS_hourly_ground_fees': item.AS_hourly_ground_fees,
            'AS_hourly_misc': item.AS_hourly_misc,
            'AS_hourly_total': item.AS_hourly_total,
            'acquisition_values':  item.acquisition_values,
            'historical_data': item.historical_data,

        })
        context = {'aircraft': aircraft_data}
        return JsonResponse(context)


@method_decorator(csrf_exempt, name='dispatch')
class AccidentsList(View):
    def get(self, request):
        accidents_number = Accident.objects.count()
        all_accidents = Accident.objects.all()
        accidents_data = []
        for item in all_accidents:
            accidents_data.append({
                'country': item.country,
                'aircraft_incident': item.aircraft_incident.aircraft_name,
                'reg': item.reg,
                'date': item.date,
                'occurrence': item.occurrence,
                'details': item.details,
            })

        data = {
            'accidents': accidents_data,
            'count': accidents_number,
        }

        return JsonResponse(data)
